### ISSUE TITLE
[Request] Config option to toggle off the Borderblocks exp. bar/H.U.D. change.

### ISSUE THREAD

**Issue by tacticalretard** [SilentChaos512/Borderblocks#3]
Minecraft Version 1.12.2 (Forge  1.12.2 - 14.23.4.2705)
Borderblocks-1.12.2-0.1.5-22
SilentLib-1.12.2-2.3.10-125

When I have Borderblocks installed, it changes the H.U.D. as expected, displaying the Borderblocks exp. bar. However, I have reason to believe this H.U.D. change may cause some kind of issue with the Scenter mod. Scenter adds the togglable ability to track ores based on type. It adds a small display to the left side of the H.U.D. which shows what ore you are tracking. However, with Borderblocks installed, this little ore tracker display only pops up when the vanilla exp. bar shows up every 5 levels, then disappears when the Borderblocks exp. bar reappears. I tested with and without Borderblocks, and the Scenter display H.U.D. element pops up perfectly fine without Borderblocks installed/changing the exp. bar. Would it be possible to add the ability to keep the vanilla exp. bar untouched and just show the Borderblocks level as a number to the side, like the reverse of what it currently does? Or maybe a way to toggle the Borderblocks exp. bar on/off in-game?

**Comment by SilentChaos512** [comment]
I'll add a config to switch the level text to the left and not change the vanilla XP bar. Changing a HUD element is tricky; one mod will always find a way to break another, no matter what you do...

**Comment by tacticalretard** [comment]
Thanks.
